all: false
dir: '{{.InterfaceDir}}'
filename: listener_mocks_test.go
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
packages:
   github.com/ihippik/wal-listener/v2/internal/listener:
     config:
       all: true